'use client';

import Link from 'next/link';

/**
 * CRITIQUE OVERVIEW PAGE
 * 
 * Hub for all critical analysis of the Western Region strategy
 * Generated by AI analysis against real MCP data
 * 
 * Last Updated: 2026-02-04
 */

const critiqueSections = [
  {
    title: 'Executive Summary',
    href: '/critique/executive-summary',
    related: '/executive-summary',
    icon: '📋',
    summary: 'Critical analysis of headline metrics, claims, and strategic framing',
    severity: 'MEDIUM',
  },
  {
    title: 'Partner Strategy',
    href: '/critique/partner-strategy',
    related: '/partner-overview',
    icon: '🤝',
    summary: 'Challenging partner revenue assumptions, team capacity, and ROI projections',
    severity: 'HIGH',
  },
  {
    title: 'Territories',
    href: '/critique/territories',
    related: '/territories',
    icon: '🗺️',
    summary: 'Validating territory metrics, seller assignments, and market sizing',
    severity: 'MEDIUM',
  },
  {
    title: 'GTM Strategy',
    href: '/critique/gtm-strategy',
    related: '/gtm-strategy',
    icon: '🎯',
    summary: 'Testing GTM pillar assumptions, target account selection, and expansion plays',
    severity: 'MEDIUM',
  },
  {
    title: 'Financial Model',
    href: '/critique/financial-model',
    related: '/financial-model',
    icon: '💰',
    summary: 'Stress-testing revenue projections, capacity constraints, and margin assumptions',
    severity: 'HIGH',
  },
  {
    title: 'Team Capacity',
    href: '/critique/team-capacity',
    related: '/team-capacity',
    icon: '👥',
    summary: 'Analyzing seller performance data, win rate claims, and coaching recommendations',
    severity: 'MEDIUM',
  },
];

const methodology = [
  {
    step: '1. Data Extraction',
    description: 'Read all site pages to extract claims, metrics, and assumptions',
    tools: 'File system analysis of src/app/**/*.tsx',
  },
  {
    step: '2. MCP Validation',
    description: 'Query live MCP servers to get actual data from Fabric lakehouse',
    tools: 'Sales MCP (3001), Labor MCP (3002), Finance MCP (3003)',
  },
  {
    step: '3. Gap Analysis',
    description: 'Compare site claims to MCP data, identify discrepancies',
    tools: 'Data comparison, statistical validation',
  },
  {
    step: '4. Strategic Critique',
    description: 'Challenge assumptions, identify risks, suggest improvements',
    tools: 'Business strategy frameworks, industry benchmarks',
  },
];

export default function CritiqueOverview() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-red-900/30 to-slate-900">
      <main className="max-w-7xl mx-auto px-6 py-16">
        {/* Header */}
        <div className="flex justify-between items-center mb-4">
          <h1 className="text-4xl md:text-5xl font-bold text-white">Strategy Critique</h1>
          <Link href="/" className="text-blue-400 hover:text-blue-300">← Back to Site</Link>
        </div>
        <p className="text-slate-300 mb-4 max-w-3xl text-lg">
          <span className="text-red-400 font-semibold">Constructive criticism</span> of the Western Region Growth Strategy.
          Every claim validated against live MCP data. Every assumption challenged.
        </p>
        <p className="text-slate-400 mb-12 max-w-3xl">
          This section was generated by AI analysis to help the executive team identify gaps, risks, and opportunities 
          for improvement before board presentation.
        </p>

        {/* Warning Banner */}
        <section className="mb-12 bg-red-900/30 rounded-xl p-6 border border-red-700/50">
          <div className="flex items-start gap-4">
            <span className="text-3xl">⚠️</span>
            <div>
              <h2 className="text-xl font-bold text-red-400 mb-2">Purpose of This Section</h2>
              <p className="text-slate-300">
                These critiques are designed to <strong>strengthen</strong> the strategy by identifying weaknesses 
                <em>before</em> external stakeholders do. This is not negativity—it&apos;s rigorous validation.
              </p>
              <p className="text-slate-400 text-sm mt-2">
                Each critique links back to the original page for easy cross-reference.
              </p>
            </div>
          </div>
        </section>

        {/* Critique Sections */}
        <section className="mb-12">
          <h2 className="text-2xl font-bold text-white mb-6">📊 Critique Sections</h2>
          <div className="grid md:grid-cols-2 gap-4">
            {critiqueSections.map((section, idx) => (
              <Link key={idx} href={section.href} className="group">
                <div className="bg-slate-800/50 rounded-xl p-6 border border-slate-700 hover:border-red-500/50 transition-all h-full">
                  <div className="flex items-start justify-between mb-3">
                    <div className="flex items-center gap-3">
                      <span className="text-3xl">{section.icon}</span>
                      <h3 className="text-lg font-bold text-white group-hover:text-red-400 transition-colors">{section.title}</h3>
                    </div>
                    <span className={`px-2 py-1 rounded text-xs font-bold ${
                      section.severity === 'HIGH' ? 'bg-red-900 text-red-300' :
                      section.severity === 'MEDIUM' ? 'bg-yellow-900 text-yellow-300' :
                      'bg-green-900 text-green-300'
                    }`}>
                      {section.severity}
                    </span>
                  </div>
                  <p className="text-slate-400 text-sm mb-3">{section.summary}</p>
                  <div className="text-xs text-slate-500">
                    Critiques: <Link href={section.related} className="text-blue-400 hover:underline">{section.related}</Link>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </section>

        {/* Methodology */}
        <section className="mb-12">
          <h2 className="text-2xl font-bold text-white mb-6">🔬 Critique Methodology</h2>
          <div className="grid md:grid-cols-4 gap-4">
            {methodology.map((step, idx) => (
              <div key={idx} className="bg-slate-800/50 rounded-xl p-5 border border-slate-700">
                <div className="text-red-400 font-bold mb-2">{step.step}</div>
                <p className="text-slate-300 text-sm mb-2">{step.description}</p>
                <p className="text-slate-500 text-xs">{step.tools}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Summary Stats */}
        <section className="mb-12 bg-gradient-to-r from-slate-800/50 to-red-800/20 rounded-xl p-8 border border-slate-700">
          <h2 className="text-2xl font-bold text-white mb-6">📈 Critique Summary</h2>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6 text-center">
            <div>
              <div className="text-4xl font-bold text-red-400">2</div>
              <div className="text-slate-400 text-sm">HIGH Severity</div>
            </div>
            <div>
              <div className="text-4xl font-bold text-yellow-400">4</div>
              <div className="text-slate-400 text-sm">MEDIUM Severity</div>
            </div>
            <div>
              <div className="text-4xl font-bold text-blue-400">6</div>
              <div className="text-slate-400 text-sm">Sections Analyzed</div>
            </div>
            <div>
              <div className="text-4xl font-bold text-green-400">37</div>
              <div className="text-slate-400 text-sm">Pages Reviewed</div>
            </div>
          </div>
        </section>

        {/* Data Sources */}
        <section className="bg-slate-900/50 rounded-xl p-6 border border-slate-600">
          <h3 className="text-sm font-bold text-slate-400 mb-3">📋 Data Validation Sources</h3>
          <div className="grid md:grid-cols-3 gap-4 text-xs text-slate-500">
            <div>
              <div className="text-blue-400 font-semibold mb-1">Sales MCP (port 3001)</div>
              <ul className="space-y-0.5">
                <li>• get_team_performance</li>
                <li>• get_win_rate_matrix</li>
                <li>• get_pipeline_by_owner</li>
                <li>• get_churn_signals</li>
              </ul>
            </div>
            <div>
              <div className="text-green-400 font-semibold mb-1">Labor MCP (port 3002)</div>
              <ul className="space-y-0.5">
                <li>• get_gold_department_metrics</li>
                <li>• get_solutions_team_roster</li>
                <li>• get_gold_utilization_summary</li>
              </ul>
            </div>
            <div>
              <div className="text-purple-400 font-semibold mb-1">Finance MCP (port 3003)</div>
              <ul className="space-y-0.5">
                <li>• get_customer_ltv</li>
                <li>• get_ar_aging</li>
                <li>• analyze_customer_profitability</li>
              </ul>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
